# Generated by Django 5.0.3 on 2024-04-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_save_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_job',
            name='saved_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
