# Generated by Django 5.0.3 on 2024-04-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_alter_save_job_saved_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='save_job',
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
