# Generated by Django 5.0.3 on 2024-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
