# Generated by Django 5.0.3 on 2024-04-25 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_user_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_profile',
            new_name='Userprofile',
        ),
    ]
